'use strict';

// Single-source acceptance test for the DSH bundle plugins.
//
// The wakeup gate text has exactly one authored source: the <WakeupGuideline>
// block of argo/rules/archgraph.instructions.md. scripts/gen-dsh-plugins.js
// renders it into dsh-argo-wakeup/index.js, and install-argo.ps1 copies that
// artifact (and dsh-argo-workspace/index.js) into ~/.dsh/plugins. These tests
// fail the moment the artifacts drift, so the deploy-time copy and the shipped
// bundle can never fork.

const { test } = require('node:test');
const assert = require('node:assert/strict');
const { readFileSync, existsSync } = require('node:fs');
const { execFileSync } = require('node:child_process');
const path = require('node:path');

const ROOT = path.resolve(__dirname, '..');
const RULE = path.join(ROOT, 'argo', 'rules', 'archgraph.instructions.md');
const WAKEUP = path.join(ROOT, 'dsh-argo-wakeup', 'index.js');
const WORKSPACE = path.join(ROOT, 'dsh-argo-workspace', 'index.js');
const GENERATOR = path.join(ROOT, 'scripts', 'gen-dsh-plugins.js');
const INSTALLER = path.join(ROOT, 'install-argo.ps1');

function normalize(text) {
  return text.replace(/\r\n/g, '\n').trim();
}

function extractRuleGate() {
  const rule = readFileSync(RULE, 'utf8').replace(/^\uFEFF/, '');
  const match = rule.match(/<WakeupGuideline>([\s\S]*?)<\/WakeupGuideline>/);
  assert.ok(match, 'the rule must contain a <WakeupGuideline> block');
  return match[1];
}

function extractPluginGate() {
  const src = readFileSync(WAKEUP, 'utf8').replace(/^\uFEFF/, '');
  const match = src.match(/const WAKEUP_GATE = (".*")\r?$/m);
  assert.ok(match, 'dsh-argo-wakeup/index.js must define WAKEUP_GATE as a JSON string literal');
  return JSON.parse(match[1]);
}

test('wakeup-single-source: the bundle gate text equals the rule <WakeupGuideline> (no fork)', () => {
  // GIVEN the rule file is the single source of the wakeup gate text
  // WHEN the shipped bundle artifact is compared with the rule
  // THEN the plugin WAKEUP_GATE value equals the rule <WakeupGuideline> value
  assert.ok(existsSync(WAKEUP), 'dsh-argo-wakeup/index.js should exist');
  assert.equal(normalize(extractPluginGate()), normalize(extractRuleGate()));
});

test('wakeup-single-source: the committed artifact is current with the generator', () => {
  // GIVEN scripts/gen-dsh-plugins.js regenerates dsh-argo-wakeup/index.js from the rule
  // WHEN the generator runs in --check mode
  // THEN it reports the committed artifact is up to date (exit 0)
  assert.ok(existsSync(GENERATOR), 'scripts/gen-dsh-plugins.js should exist');
  const out = execFileSync(process.execPath, [GENERATOR, '--check'], { cwd: ROOT, encoding: 'utf8' });
  assert.match(out, /up to date/);
});

test('installer-copies-single-source: install-argo.ps1 copies the artifacts instead of embedding templates', () => {
  // GIVEN the installer must not carry its own copy of either plugin
  // WHEN install-argo.ps1 is inspected
  // THEN it copies both single-source artifacts and no inline plugin template remains
  const script = readFileSync(INSTALLER, 'utf8');
  assert.equal(
    (script.match(/Copy-Item -Force -Path \$source -Destination \$indexPath/g) || []).length,
    2,
    'both the wakeup and workspace plugins must be deployed by copying the single source',
  );
  assert.match(script, /dsh-argo-wakeup'\) 'index\.js'/, 'must copy dsh-argo-wakeup/index.js');
  assert.match(script, /dsh-argo-workspace'\) 'index\.js'/, 'must copy dsh-argo-workspace/index.js');
  assert.doesNotMatch(script, /\$gateJson/, 'the inline wakeup template must be gone');
  assert.doesNotMatch(script, /dsh-argo-workspace - generated by install-argo/, 'the inline workspace template must be gone');
  assert.ok(existsSync(WORKSPACE), 'dsh-argo-workspace/index.js should exist');
});
