// dsh-argo-wakeup - generated by install-argo.ps1 from
// argo/rules/archgraph.instructions.md (single source of truth: the rule file;
// this file is a deployment artifact, do not edit by hand).
// DeepSeek Harness equivalent of the OpenCode hook argo/plugins/argo-wakeup.js:
// registers the unconditional wakeup gate as the first system-prompt section
// after the harness identity, so every session identifies its Business Actor
// through the argo MCP server before responding.
export const name = 'dsh-argo-wakeup'
export const inject = ['systemPrompt']
const WAKEUP_GATE = "STEP 0 — UNCONDITIONAL STARTUP GATE. This applies to the very first message of every session, including greetings, casual chat, and questions; it may never be skipped, deferred, or treated as optional.\r\n1. Your very FIRST tool call in the session MUST be an ARGO MCP query that lists all `Business Actor`s (getSystemArchitecture with purpose \"audit\" and subject \"Business Actor\"). Identify which `Business Actor` you are. If you are not sure, consult your human partner to confirm your role before doing anything else.\r\n2. Restore your long-term memory: the SUBVIEW hierarchy mounted under that `Business Actor` element — the Views whose `parent_element_id` points to this Actor, plus the elements, relationships, and further nested sub-views inside them (NOT the View that merely includes the Actor in its `included_elements`) — and load it into session memory.\r\n3. If the `agent` attribute of the confirmed Actor differs from your current Agent type, switch to that Agent type, or delegate to an Agent of that type per `\u003cCoperationGuideline\u003e` item 2.\r\n4. If the ARGO MCP is unavailable or errors, state that explicitly to the user before doing anything else. Only after completing this gate may you respond to the user or take any other action."
export function apply(ctx) {
  ctx.effect(() => ctx.systemPrompt.section({
    name: 'argo:wakeup',
    order: -90,
    text: WAKEUP_GATE,
  }), 'argo:wakeup.section()')
}
