// dsh-argo-wakeup - generated by scripts/gen-dsh-plugins.js from
// argo/rules/archgraph.instructions.md (single source of truth: the rule file;
// this file is a deployment artifact, do not edit by hand).
// DeepSeek Harness equivalent of the OpenCode hook argo/plugins/argo-wakeup.js:
// registers the unconditional wakeup gate as the first system-prompt section
// after the harness identity, so every session identifies its Business Actor
// through the argo MCP server before responding.
export const name = 'dsh-argo-wakeup'
export const inject = ['systemPrompt']
const WAKEUP_GATE = "STEP 0 — UNCONDITIONAL STARTUP GATE. Applies to the very first message of every session, greetings and chat included; never skip, defer, or treat it as optional.\n1. Your first tool call MUST be an ARGO MCP query that lists all Actor elements. The Actor element type is reported by `queryNeo4jGraph` with `{schema:true}` as `actorElementType` (`Business Actor` under the default ArgoBument schema, or whatever the workspace's own `.argo/schema` bundle declares; `null` means that schema has no Actor concept — then skip Actor identification). Confirm which Actor you are; if unsure, ask your human partner before anything else.\n2. Restore memory: load ONLY the T1 working-memory digest — your T1 summary, the most recent/active memory cards, and any session hooks (unfinished items from the last session). Do NOT bulk-load the T2 long-term memory or T3 archive; recall them on demand via `memory_search`, then read full content with `getIntentElementContext`. T2 is a recall target, not as a bulk context load.\n3. If the Actor's `agent` attribute differs from your type, switch to it or delegate per `<CoperationGuideline>` item 2.\n4. If the ARGO MCP is unavailable or errors, say so before doing anything else."
export function apply(ctx) {
  ctx.effect(() => ctx.systemPrompt.section({
    name: 'argo:wakeup',
    order: -90,
    text: WAKEUP_GATE,
  }), 'argo:wakeup.section()')
}
