// dsh-argo-workspace - generated by install-argo.ps1 (single source of truth:
// the installer; this file is a deployment artifact, do not edit by hand).
//
// Direct MCP bridge to the argo server for DeepSeek Harness. Registers every
// argo tool as mcp__argo__* and injects the current session's workspace
// directory (SessionHeader.cwd) as the per-call `workspaceRoot` argument, so
// one dsh instance follows whichever workspace the user switched to - the
// model sees no extra parameters and no internal tool names. The argo server
// honors the injected workspaceRoot unconditionally.
//
// Zero dependencies on purpose: implements the minimal MCP stdio client
// (JSON-RPC 2.0, one JSON object per line) with Node built-ins only, so the
// plugin runs from any DSH layout without resolving @modelcontextprotocol/sdk.
import { spawn } from 'node:child_process'
import readline from 'node:readline'
import { fileURLToPath } from 'node:url'

export const name = 'dsh-argo-workspace'
export const inject = ['tools']

// 包内默认：<pkg>/argo/scripts/argo-mcp-server.js —— 随包走，跨机器可移植。
const DEFAULT_SERVER_PATH = fileURLToPath(
  new URL('../argo/scripts/argo-mcp-server.js', import.meta.url),
)

/** Minimal MCP stdio client over the argo server process. */
function createArgoClient(serverPath, env, cwd) {
  const child = spawn('node', [serverPath], {
    stdio: ['pipe', 'pipe', 'pipe'],
    env,
    ...(cwd ? { cwd } : {}),
  })
  const pending = new Map()
  let nextId = 1
  readline.createInterface({ input: child.stdout }).on('line', (line) => {
    let message
    try { message = JSON.parse(line) } catch { return }
    if (message && typeof message.id === 'number' && pending.has(message.id)) {
      const { resolve, reject } = pending.get(message.id)
      pending.delete(message.id)
      if (message.error) reject(new Error(JSON.stringify(message.error)))
      else resolve(message.result)
    }
  })
  child.stderr.on('data', () => {}) // drain; the argo server logs to stderr
  const request = (method, params) => new Promise((resolve, reject) => {
    const id = nextId++
    pending.set(id, { resolve, reject })
    child.stdin.write(JSON.stringify({ jsonrpc: '2.0', id, method, params }) + '\n')
  })
  return {
    request,
    notify: (method, params) => {
      child.stdin.write(JSON.stringify({ jsonrpc: '2.0', method, params }) + '\n')
    },
    close: () => child.kill(),
  }
}

/** Connect, list tools, register them, and keep the client until disposal. */
export async function apply(ctx, config) {
  const serverPath = config.serverPath
    ?? process.env.ARGO_SERVER_PATH
    ?? DEFAULT_SERVER_PATH
  const workspaces = Array.isArray(config.workspaces) ? config.workspaces : []
  const env = { ...process.env }
  if (workspaces.length > 0) env.ARGO_WORKSPACE_ROOTS = workspaces.join(';')
  const client = createArgoClient(serverPath, env, config.cwd)
  ctx.effect(() => () => client.close(), 'dsh-argo-workspace.dispose()')

  let tools = []
  try {
    await client.request('initialize', {
      protocolVersion: '2024-11-05',
      capabilities: {},
      clientInfo: { name: 'dsh-argo-workspace', version: '0.1.0' },
    })
    client.notify('notifications/initialized', {})
    const listed = await client.request('tools/list', {})
    tools = (listed && Array.isArray(listed.tools)) ? listed.tools : []
  } catch (error) {
    console.warn(`[dsh-argo-workspace] failed to connect to the argo MCP server (${serverPath}): ${error && error.message ? error.message : error}`)
    return
  }

  const disposers = []
  for (const tool of tools) {
    const publicName = 'mcp__argo__' + tool.name
    disposers.push(ctx.tools.register({
      name: publicName,
      description: tool.description ?? '',
      parameters: tool.inputSchema,
      output: {
        schema: {
          type: 'object',
          properties: {
            content: { type: 'array', items: {} },
            structuredContent: {},
          },
          required: ['content'],
          additionalProperties: false,
        },
        render: (_args, value) => value.content,
      },
      execute: async (args, exec) => {
        // SessionHeader.cwd (the durable session workspace), NOT
        // requestHeader() — that returns the request EpochHeader
        // (config/system/tools) which has no cwd field.
        const sessionCwd = exec && exec.agent && exec.agent.session
          ? exec.agent.session.header?.cwd
          : undefined
        const injected = { ...(args && typeof args === 'object' ? args : {}) }
        if (typeof sessionCwd === 'string' && sessionCwd !== '') {
          injected.workspaceRoot = sessionCwd
        }
        if (exec && exec.signal && exec.signal.aborted) {
          throw new Error('aborted')
        }
        const result = await client.request('tools/call', {
          name: tool.name,
          arguments: injected,
        })
        const text = Array.isArray(result.content)
          ? result.content
              .map((block) => block && block.type === 'text' && typeof block.text === 'string'
                ? block.text
                : JSON.stringify(block))
              .join('\n')
          : (result.toolResult !== undefined ? JSON.stringify(result.toolResult) : '(no output)')
        if (result.isError === true) throw new Error(text)
        return {
          content: [{ type: 'text', text }],
          ...(result.structuredContent !== undefined ? { structuredContent: result.structuredContent } : {}),
        }
      },
    }))
  }
  ctx.effect(() => () => {
    for (const dispose of disposers) dispose()
  }, 'dsh-argo-workspace.tools')
}
